#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf constant/polyMesh/sets

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite
runApplication splitMeshRegions -cellZones -overwrite

for i in air box substrate container wire space target magnet1 magnet2 ring
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

#-- Run on single processor
runApplication plasmaInitialise
runApplication `getApplication`

# Decompose
#for i in air box box
#do
#   decomposePar -region $i > log.decomposePar.$i 2>&1
#done

## Run
#runParallel `getApplication` 2

## Reconstruct
#for i in air box box
#do
#   reconstructPar -region $i > log.reconstructPar.$i 2>&1
#done

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
